### ISSUE TITLE
Concatenate search endpoint and filters

### ISSUE THREAD

**Issue by uf0** [C2DH/miller#3]

**Comment by danieleguido** [comment]
The commit 1c77376b7a4a384ad6a8c16778115542979f9dba should fix this. We created a new model field in both [Document](https://github.com/C2DH/miller/blob/master/miller/models/document.py#L107) and [Story](https://github.com/C2DH/miller/blob/master/miller/models/story.py#L123) model named `search_vector` of type `SearchVectorField` [see official django doc](https://docs.djangoproject.com/fr/1.11/ref/contrib/postgres/search/#django.contrib.postgres.search.SearchVectorField)

Both models expose the `update_search_vector` class method which takes the contents to index from instance properties and index them into `search_vector`. For the moment, **there is no automatic update** of the field. However you can use the custom django management command `task`:

```
python manage.py task update_search_vectors --model=document

python manage.py task update_search_vectors --model=story
```

Note that you can also specify a `--pk` argument if you want to update *only one specific item*:

```
python manage.py task update_search_vectors --model=story --pk=1234
```

To look for results, you can use the http param `q=` in `/api/document` and `/api/story` endpoints, and this can be used in conjunction with **filters** and **facets**. Have a quick look at the `miller.api.utils.Glue` class. 

Both in `Story` and in `Document` class you can find the `@staticmethod get_search_Q(query)` which produces a `django.db.models.Q` that can be used in filters.
This translates a natural query, e.g. `"cat* dog"` into a ts_query that can be used with postgresql search_vector (`"cat:* & dog"`). 
For this purpose, we created a subclass of `SearchQuery` ([see docs](https://docs.djangoproject.com/fr/1.11/ref/contrib/postgres/search/#searchquery)) namely `miller.postgres.RawSearchQuery` in order to circumvent the [limitation of the postgresql command plainto_tsquery](https://www.postgresql.org/docs/current/static/textsearch-controls.html#TEXTSEARCH-PARSING-QUERIES)).
