### ISSUE TITLE
add typeahead endpoint api

### ISSUE THREAD

**Issue by uf0** [C2DH/miller#4]

**Comment by danieleguido** [comment]
Very simple endpoint can be: `/api/services/suggest?q=`

**Comment by uf0** [comment]
should we add a parameters to specify on which part of the collection create the ngrams?

e.g.: on the 'map' page the suggestions should be refer only to the documents that have coordinates.

`/api/services/suggest?q=blibli&filter={'data__coordinates__isnull':False}`

**Comment by danieleguido** [comment]
Apparently we can use postgresql - once it's correctly configured 👍  cfr . http://rachbelaid.com/postgres-full-text-search-is-good-enough/#1
I'd also suggest to substitute whoosh search engine with postgresql

**Comment by danieleguido** [comment]
I suggest we fill a proper table containing all the possible (and valid) trigram combination, like https://www.sitepoint.com/awesome-autocomplete-trigram-search-in-rails-and-postgresql/
What do do with the multilanguage? Should we use the `config=simple`?

**Comment by bianchimro** [comment]
is the language known at search time? or should the engine return results in all available languages?

**Comment by danieleguido** [comment]
@bianchimro I had the same doubt, since the language is known; but at the end the best option would be to get results no matter the language, so that things stay simple and coherent to what you get now on document and story search endpoint. Moreover it will be a lot easier for "multi-language people" ;)

How to deal with @uf0 suggestion to filter typeahead? If we use the `document.search_vector` field, we will get this out of the box; on the other hand, if we use a trigram table, we can somehow point to the related document. This way we apply the doc filters and we limit the list of trigrams to the related ones, but the trigram table stay simple... Any ideas?

**Comment by danieleguido** [comment]
Hi @bianchimro, I've added a Ngrams model in the `feature/typeahead` branch. In Ngram model you can find a very basic ngram tokenizer. 
Fill the ngram table (to test, use one document) with:
```
python manage.py task update_ngrams_table --model=document --pk=547
```
This adds bigrams and trigrams to the ngrams table from the indexable fields in document model.

**Comment by danieleguido** [comment]
Closed, ref to master branch.
